routes/web.php
<?php

//use Illuminate\Support\Facades\Route;
//use App\impresion_paginas;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

/*Route::get('/activarcron', function () {
    return view('layouts.activarcron');
});*/

Auth::routes();


Route::get('/home', 'copController@index')->name('home');

Route::get('/user', 'UsersController@index')->name('administradores');

Route::get('/historico', 'copController@historico');

Route::get('/multifun', 'copController@multifuncionales');

Route::get('/actcron', 'copController@activarcron');

Route::resource('asignar', 'AsignarpaginasController');

app/asignarpaginas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class asignarpaginas extends Model
{
    //
    protected $table = 'asignarpaginas';
}

app/Http/Controllers/AsignarpaginasController.php
<?php

namespace App\Http\Controllers;

use App\asignarpaginas;
use App\permiso_impresion;
use App\impresiones_usuario;
use Illuminate\Http\Request;
use DB;

class AsignarpaginasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $asignar = asignarpaginas::all();
        return view('asignarpaginas.index', compact('asignar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\asignarpaginas  $asignarpaginas
     * @return \Illuminate\Http\Response
     */
    public function show(asignarpaginas $asignarpaginas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\asignarpaginas  $asignarpaginas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $asignarnumero = asignarpaginas::findOrFail($id);
        return view('asignarpaginas.edit', compact('asignarnumero'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\asignarpaginas  $asignarpaginas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $valid = $request->validate([
            'PagCout'=>'required'
        ]);
                
        $usuario = asignarpaginas::findOrFail($id);
        
        $usuario_impre = impresiones_usuario::findOrFail($id);

        $valorCout = permiso_impresion::findOrFail($id); 

        //  Validaciones de entrada para el control de impresiones 

            if ( $valorCout->Cout != null ) {
                
                if ( $valid['PagCout'] > $valorCout->Cout ) {
                    $result = $valid['PagCout'] + $valorCout->Cout;
                    //$result = ($tmp + $valorCout->Cout);
                }
                else if ( $valid['PagCout'] < $valorCout->Cout ) {
                    $tmp = ( $usuario->PagCout - $valid['PagCout'] );
                    $result = ($valorCout->Cout - $tmp);
                }

                permiso_impresion::where('id', $id)->update(array('Cout' => $result));
            
            }

            asignarpaginas::whereId($id)->update($valid);
            
            if ( $usuario->PagCout == null || $usuario->PagCout == "" ) {
                
                $file = fopen("atemp.ps1", "w");
                $script = '$sama = Get-ADUser -Filter "Name -eq '.$usuario->UserPc.'" | Select-Object samaccountname; Add-ADGroupMember -Identity act_grupo -Members $sama.samaccountname';
                fwrite($file,$script. PHP_EOL);
                fclose($file);
                shell_exec("powershell.exe .\atemp.ps1");

            }


        //$asignarnumero = asignarpaginas::findOrFail($id);
        //return view('asignarpaginas.edit', compact('asignarnumero'));
        $asignar = asignarpaginas::all();
        return view('asignarpaginas.index', compact('asignar'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\asignarpaginas  $asignarpaginas
     * @return \Illuminate\Http\Response
     */
    public function destroy(asignarpaginas $asignarpaginas)
    {
        //
    }
}

resources/views/asignarpaginas/edit.blade.php
@extends('layouts.plantilla')
@section('contenidoGeneral')

	<div class="dashboard-wrapper">
		<div class="container-fluid dashboard-content ">
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-8">
					<div class="page-header">
						<h2 class="pageheader-title">Control COP - control de impresiones </h2> </div>
					</div>
				<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
					<div class="page-header" align="right"> <img class="logo-img" src="{{ asset('assets/images/fergon.png') }}" alt="logo" height="45"> </div>
				</div>
			</div>			
			<div class="row">
                    <!-- ============================================================== -->
                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2"></div>
                    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-8">
                        <div class="card">
                            <div class="card-header">
                                <div style="text-align: center; margin-bottom: 30px;">
                                    <img class="logo-img" src="{{ asset('assets/images/usuario.png') }}" alt="logo" height="75">
                                    <span style="font-size: 23px; text-align: center;color: #898989; font-family: arial;">Asignar paginas</span>
                                </div>
                            </div>
                            <div class="card-body">
                            	@if ($errors->any())
								  <div class="alert alert-danger">
									<ul>
										@foreach ($errors->all() as $error)
										  <li>{{ $error }}</li>
										@endforeach
									</ul>
								  </div><br />
								@endif
                                <form method="post" action=" {{ route('asignar.update', $asignarnumero->id) }}">
                                @method('PATCH') 
            					@csrf
                                <div class="row form-group">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="position:relative; top:7px;" title="Nombre de pila o primer nombre">Nombre de pila o primer nombre:</label>
                                    </div>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="UserPc" value=" {{ $asignarnumero->UserPc}}"  autocomplete="off" disabled="">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="control-label" style="position:relative; top:7px;" title="Nombre completo del usuario">Cantidad de paginas:</label>
                                    </div>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="PagCout" value="{{ $asignarnumero->PagCout }}"  autocomplete="off" autofocus="" >
                                    </div>
                                       
                                </div>
                            </div>

                            <div class="modal-footer">
                            	<button type="submit" class="btn btn-primary">Actualizar</button>

                            </form>
                                <a href="{{ url('/asignar') }}" class="btn btn-default"><span class="fa fa-close"></span> Cancelar</a>
                                
                            </div>
                                

                        </div>
                    </div>
                    
                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2"></div>
                </div>

		</div>
	</div>


@endsection

resources/views/asignarpaginas/index.blade.php
@extends('layouts.plantilla')
@section('contenidoGeneral')

	<div class="dashboard-wrapper">
		<div class="container-fluid dashboard-content ">
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-8">
					<div class="page-header">
						<h2 class="pageheader-title">Control COP - control de impresiones </h2> </div>
					</div>
				<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
					<div class="page-header" align="right"> <img class="logo-img" src="{{ asset('assets/images/fergon.png') }}" alt="logo" height="45"> </div>
				</div>
			</div>			

			<div class="row">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<table id="example" class="table table-striped table-bordered second" style="width:100%">
									<thead>
										<tr>
											<th>ID</th>
											<th>Usuario AD</th>
											<th>Equipo</th>
											<th>Paginas asignadas</th>
											<th>PC</th>
											<th>Acción</th>
										</tr>
									</thead>
									<tbody>
									@foreach ($asignar as $dato)
										<tr>
											<td>{{ $dato->id }}</td>
											<td>{{ $dato->UserPc }}</td>
											<td>{{ $dato->aEquipo }}</td>
											<td>{{ $dato->PagCout }}</td>
											<td>{{ $dato->users }}</td>
											<td>
												@if ($dato->PagCout != '' || $dato->PagCout != null)
													<a href="{{ route('asignar.edit',$dato->id)}}" class="btn btn-primary">Editar</a>	
													@else
													<button class="btn btn-default" disabled="">Editar</button>
												@endif
												
											</td>
										</tr>
									@endforeach												  
									</tbody>
										<tfoot>
											<tr>
												<th>ID</th>
												<th>Usuario AD</th>
												<th>Equipo</th>
												<th>Paginas asignadas</th>
												<th>PC</th>
												<th>Acción</th>
											</tr>
										</tfoot>
								</table>
							</div>
						</div>
					</div>
			   </div>
			</div>

		</div>
	</div>


@endsection